const {SchemaType} = require("firebase/ai");
const {geminiCreateContent} = require("./ai");
const fs = require("fs");
const path = require("path");

const schemaOutput = {
  type: SchemaType.OBJECT,
  properties: {
    id: {type: SchemaType.STRING},
    name: {type: SchemaType.STRING},
    nativeName: {type: SchemaType.STRING},
    indonesianName: {type: SchemaType.STRING},
    icon: {type: SchemaType.STRING},
    currencyCode: {type: SchemaType.STRING},
    currencySymbol: {type: SchemaType.STRING},
    currencyName: {type: SchemaType.STRING},
    emojiFlag: {type: SchemaType.STRING},
    continent: {type: SchemaType.STRING},
    subregion: {type: SchemaType.STRING},
    callingCode: {type: SchemaType.STRING},
    languages: {
      type: SchemaType.ARRAY,
      items: {type: SchemaType.STRING},
    },
    currencyDecimals: {type: SchemaType.NUMBER},
    iso2: {type: SchemaType.STRING},
    iso3: {type: SchemaType.STRING},
    numericCode: {type: SchemaType.STRING},
    timezones: {
      type: SchemaType.ARRAY,
      items: {type: SchemaType.STRING},
    },
    tld: {type: SchemaType.STRING},
  },
  required: [
    "id",
    "name",
    "nativeName",
    "indonesianName",
    "icon",
    "currencyCode",
    "currencySymbol",
    "currencyName",
    "emojiFlag",
    "continent",
    "subregion",
    "callingCode",
    "languages",
    "currencyDecimals",
    "iso2",
    "iso3",
    "numericCode",
    "timezones",
    "tld",
  ],
};

const input = `{
  ABK: {
    id: "ABK",
    name: "Abkhazia",
    nativeName: "аҧсуа",
    indonesianName: "Abjasida",
    icon: icons.Abkhazia,
    currencyCode: "RUB",
    currencySymbol: "₽",
    currencyName: "Ruble",
  },
  AFG: {
    id: "AFG",
    name: "Afghanistan",
    nativeName: "افغانستان",
    indonesianName: "Afganistan",
    icon: icons.Afghanistan,
    currencyCode: "AFN",
    currencySymbol: "؋",
    currencyName: "Afghani",
  },
  ALA: {
    id: "ALA",
    name: "Aland Islands",
    nativeName: "Åland",
    indonesianName: "Kepulauan Aland",
    icon: icons.AlandIslands,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  ALB: {
    id: "ALB",
    name: "Albania",
    nativeName: "Shqipëri",
    indonesianName: "Albania",
    icon: icons.Albania,
    currencyCode: "ALL",
    currencySymbol: "L",
    currencyName: "Lek",
  },
  DZA: {
    id: "DZA",
    name: "Algeria",
    nativeName: "الجزائر",
    indonesianName: "Aljazair",
    icon: icons.Algeria,
    currencyCode: "DZD",
    currencySymbol: "د.ج",
    currencyName: "Algerian Dinar",
  },
  ASM: {
    id: "ASM",
    name: "American Samoa",
    nativeName: "American Samoa",
    indonesianName: "Samoa Amerika",
    icon: icons.AmericanSamoa,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  AND: {
    id: "AND",
    name: "Andorra",
    nativeName: "Andorra",
    indonesianName: "Andorra",
    icon: icons.Andorra,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  AGO: {
    id: "AGO",
    name: "Angola",
    nativeName: "Angola",
    indonesianName: "Angola",
    icon: icons.Angola,
    currencyCode: "AOA",
    currencySymbol: "Kz",
    currencyName: "Kwanza",
  },
  AIA: {
    id: "AIA",
    name: "Anguilla",
    nativeName: "Anguilla",
    indonesianName: "Anguilla",
    icon: icons.Anguilla,
    currencyCode: "XCD",
    currencySymbol: "$",
    currencyName: "East Caribbean Dollar",
  },
  ATG: {
    id: "ATG",
    name: "Antigua and Barbuda",
    nativeName: "Antigua and Barbuda",
    indonesianName: "Antigua dan Barbuda",
    icon: icons.AntiguaAndBarbuda,
    currencyCode: "XCD",
    currencySymbol: "$",
    currencyName: "East Caribbean Dollar",
  },
  ARG: {
    id: "ARG",
    name: "Argentina",
    nativeName: "Argentina",
    indonesianName: "Argentina",
    icon: icons.Argentina,
    currencyCode: "ARS",
    currencySymbol: "$",
    currencyName: "Argentine Peso",
  },
  ARM: {
    id: "ARM",
    name: "Armenia",
    nativeName: "Հայաստան",
    indonesianName: "Armenia",
    icon: icons.Armenia,
    currencyCode: "AMD",
    currencySymbol: "֏",
    currencyName: "Armenian Dram",
  },
  ABW: {
    id: "ABW",
    name: "Aruba",
    nativeName: "Aruba",
    indonesianName: "Aruba",
    icon: icons.Aruba,
    currencyCode: "AWG",
    currencySymbol: "ƒ",
    currencyName: "Aruban Florin",
  },
  AUS: {
    id: "AUS",
    name: "Australia",
    nativeName: "Australia",
    indonesianName: "Australia",
    icon: icons.Australia,
    currencyCode: "AUD",
    currencySymbol: "$",
    currencyName: "Australian Dollar",
  },
  AUT: {
    id: "AUT",
    name: "Austria",
    nativeName: "Österreich",
    indonesianName: "Austria",
    icon: icons.Austria,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  AZE: {
    id: "AZE",
    name: "Azerbaijan",
    nativeName: "Azərbaycan",
    indonesianName: "Azerbaijan",
    icon: icons.Azerbaijan,
    currencyCode: "AZN",
    currencySymbol: "₼",
    currencyName: "Azerbaijani Manat",
  },
  AZO: {
    id: "AZO",
    name: "Azores Islands",
    nativeName: "Açores",
    indonesianName: "Kepulauan Azores",
    icon: icons.AzoresIslands,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  BHS: {
    id: "BHS",
    name: "Bahamas",
    nativeName: "Bahamas",
    indonesianName: "Bahama",
    icon: icons.Bahamas,
    currencyCode: "BSD",
    currencySymbol: "$",
    currencyName: "Bahamian Dollar",
  },
  BHR: {
    id: "BHR",
    name: "Bahrain",
    nativeName: "البحرين",
    indonesianName: "Bahrain",
    icon: icons.Bahrain,
    currencyCode: "BHD",
    currencySymbol: ".د.ب",
    currencyName: "Bahraini Dinar",
  },
  IBE: {
    id: "IBE",
    name: "Balearic Islands",
    nativeName: "Illes Balears",
    indonesianName: "Kepulauan Balearik",
    icon: icons.BalearicIslands,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  BGD: {
    id: "BGD",
    name: "Bangladesh",
    nativeName: "বাংলাদেশ",
    indonesianName: "Bangladesh",
    icon: icons.Bangladesh,
    currencyCode: "BDT",
    currencySymbol: "৳",
    currencyName: "Taka",
  },
  BRB: {
    id: "BRB",
    name: "Barbados",
    nativeName: "Barbados",
    indonesianName: "Barbados",
    icon: icons.Barbados,
    currencyCode: "BBD",
    currencySymbol: "$",
    currencyName: "Barbadian Dollar",
  },
  EUS: {
    id: "EUS",
    name: "Basque Country",
    nativeName: "Euskadi",
    indonesianName: "Negara Basque",
    icon: icons.BasqueCountry,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  BLR: {
    id: "BLR",
    name: "Belarus",
    nativeName: "Беларусь",
    indonesianName: "Belarus",
    icon: icons.Belarus,
    currencyCode: "BYN",
    currencySymbol: "Br",
    currencyName: "Belarusian Ruble",
  },
  BEL: {
    id: "BEL",
    name: "Belgium",
    nativeName: "België",
    indonesianName: "Belgia",
    icon: icons.Belgium,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  BLZ: {
    id: "BLZ",
    name: "Belize",
    nativeName: "Belize",
    indonesianName: "Belize",
    icon: icons.Belize,
    currencyCode: "BZD",
    currencySymbol: "$",
    currencyName: "Belize Dollar",
  },
  BEN: {
    id: "BEN",
    name: "Benin",
    nativeName: "Bénin",
    indonesianName: "Benin",
    icon: icons.Benin,
    currencyCode: "XOF",
    currencySymbol: "CFA",
    currencyName: "West African CFA Franc",
  },
  BMU: {
    id: "BMU",
    name: "Bermuda",
    nativeName: "Bermuda",
    indonesianName: "Bermuda",
    icon: icons.Bermuda,
    currencyCode: "BMD",
    currencySymbol: "$",
    currencyName: "Bermudian Dollar",
  },
  BTN: {
    id: "BTN",
    name: "Bhutan",
    nativeName: "འབྲུག",
    indonesianName: "Bhutan",
    icon: icons.Bhutan1,
    currencyCode: "BTN",
    currencySymbol: "Nu.",
    currencyName: "Ngultrum",
  },
  BOL: {
    id: "BOL",
    name: "Bolivia",
    nativeName: "Bolivia",
    indonesianName: "Bolivia",
    icon: icons.Bolivia,
    currencyCode: "BOB",
    currencySymbol: "Bs.",
    currencyName: "Boliviano",
  },
  BES: {
    id: "BES",
    name: "Bonaire",
    nativeName: "Bonaire",
    indonesianName: "Bonaire",
    icon: icons.Bonaire,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  BIH: {
    id: "BIH",
    name: "Bosnia and Herzegovina",
    nativeName: "Bosna i Hercegovina",
    indonesianName: "Bosnia dan Herzegovina",
    icon: icons.BosniaAndHerzegovina,
    currencyCode: "BAM",
    currencySymbol: "KM",
    currencyName: "Convertible Mark",
  },
  BWA: {
    id: "BWA",
    name: "Botswana",
    nativeName: "Botswana",
    indonesianName: "Botswana",
    icon: icons.Botswana,
    currencyCode: "BWP",
    currencySymbol: "P",
    currencyName: "Pula",
  },
  BRA: {
    id: "BRA",
    name: "Brazil",
    nativeName: "Brasil",
    indonesianName: "Brasil",
    icon: icons.Brazil,
    currencyCode: "BRL",
    currencySymbol: "R$",
    currencyName: "Brazilian Real",
  },
  BCO: {
    id: "BCO",
    name: "British Columbia",
    nativeName: "British Columbia",
    indonesianName: "British Columbia",
    icon: icons.BritishColumbia,
    currencyCode: "CAD",
    currencySymbol: "$",
    currencyName: "Canadian Dollar",
  },
  IOT: {
    id: "IOT",
    name: "British Indian Ocean Territory",
    nativeName: "British Indian Ocean Territory",
    indonesianName: "Wilayah Samudra Hindia Britania",
    icon: icons.BritishIndianOceanTerritory,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  VGB: {
    id: "VGB",
    name: "British Virgin Islands",
    nativeName: "British Virgin Islands",
    indonesianName: "Kepulauan Virgin Britania Raya",
    icon: icons.BritishVirginIslands,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  BRN: {
    id: "BRN",
    name: "Brunei",
    nativeName: "Brunei",
    indonesianName: "Brunei",
    icon: icons.Brunei,
    currencyCode: "BND",
    currencySymbol: "$",
    currencyName: "Brunei Dollar",
  },
  BGR: {
    id: "BGR",
    name: "Bulgaria",
    nativeName: "България",
    indonesianName: "Bulgaria",
    icon: icons.Bulgaria,
    currencyCode: "BGN",
    currencySymbol: "лв",
    currencyName: "Bulgarian Lev",
  },
  BFA: {
    id: "BFA",
    name: "Burkina Faso",
    nativeName: "Burkina Faso",
    indonesianName: "Burkina Faso",
    icon: icons.BurkinaFaso,
    currencyCode: "XOF",
    currencySymbol: "CFA",
    currencyName: "West African CFA Franc",
  },
  BDI: {
    id: "BDI",
    name: "Burundi",
    nativeName: "Burundi",
    indonesianName: "Burundi",
    icon: icons.Burundi,
    currencyCode: "BIF",
    currencySymbol: "FBu",
    currencyName: "Burundian Franc",
  },
  KHM: {
    id: "KHM",
    name: "Cambodia",
    nativeName: "កម្ពុជា",
    indonesianName: "Kamboja",
    icon: icons.Cambodia,
    currencyCode: "KHR",
    currencySymbol: "៛",
    currencyName: "Riel",
  },
  CMR: {
    id: "CMR",
    name: "Cameroon",
    nativeName: "Cameroun",
    indonesianName: "Kamerun",
    icon: icons.Cameroon,
    currencyCode: "XAF",
    currencySymbol: "FCFA",
    currencyName: "Central African CFA Franc",
  },
  CAN: {
    id: "CAN",
    name: "Canada",
    nativeName: "Canada",
    indonesianName: "Kanada",
    icon: icons.Canada,
    currencyCode: "CAD",
    currencySymbol: "$",
    currencyName: "Canadian Dollar",
  },
  ICN: {
    id: "ICN",
    name: "Canary Islands",
    nativeName: "Canarias",
    indonesianName: "Kepulauan Canary",
    icon: icons.CanaryIslands,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  CPV: {
    id: "CPV",
    name: "Cape Verde",
    nativeName: "Cabo Verde",
    indonesianName: "Tanjung Verde",
    icon: icons.CapeVerde,
    currencyCode: "CVE",
    currencySymbol: "Esc",
    currencyName: "Cape Verdean Escudo",
  },
  CYM: {
    id: "CYM",
    name: "Cayman Islands",
    nativeName: "Cayman Islands",
    indonesianName: "Kepulauan Cayman",
    icon: icons.CaymanIslands,
    currencyCode: "KYD",
    currencySymbol: "$",
    currencyName: "Cayman Islands Dollar",
  },
  CAF: {
    id: "CAF",
    name: "Central African Republic",
    nativeName: "République centrafricaine",
    indonesianName: "Republik Afrika Tengah",
    icon: icons.CentralAfricanRepublic,
    currencyCode: "XAF",
    currencySymbol: "FCFA",
    currencyName: "Central African CFA Franc",
  },
  CEU: {
    id: "CEU",
    name: "Ceuta",
    nativeName: "Ceuta",
    indonesianName: "Ceuta",
    icon: icons.Ceuta,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  TCD: {
    id: "TCD",
    name: "Chad",
    nativeName: "Tchad",
    indonesianName: "Chad",
    icon: icons.Chad,
    currencyCode: "XAF",
    currencySymbol: "FCFA",
    currencyName: "Central African CFA Franc",
  },
  CHL: {
    id: "CHL",
    name: "Chile",
    nativeName: "Chile",
    indonesianName: "Chili",
    icon: icons.Chile,
    currencyCode: "CLP",
    currencySymbol: "$",
    currencyName: "Chilean Peso",
  },
  CHN: {
    id: "CHN",
    name: "China",
    nativeName: "中国",
    indonesianName: "Tiongkok",
    icon: icons.China,
    currencyCode: "CNY",
    currencySymbol: "¥",
    currencyName: "Yuan",
  },
  CXR: {
    id: "CXR",
    name: "Christmas Island",
    nativeName: "Christmas Island",
    indonesianName: "Pulau Natal",
    icon: icons.ChristmasIsland,
    currencyCode: "AUD",
    currencySymbol: "$",
    currencyName: "Australian Dollar",
  },
  CCK: {
    id: "CCK",
    name: "Cocos Island",
    nativeName: "Cocos (Keeling) Islands",
    indonesianName: "Kepulauan Cocos (Keeling)",
    icon: icons.CocosIsland,
    currencyCode: "AUD",
    currencySymbol: "$",
    currencyName: "Australian Dollar",
  },
  COL: {
    id: "COL",
    name: "Colombia",
    nativeName: "Colombia",
    indonesianName: "Kolombia",
    icon: icons.Colombia,
    currencyCode: "COP",
    currencySymbol: "$",
    currencyName: "Colombian Peso",
  },
  COM: {
    id: "COM",
    name: "Comoros",
    nativeName: "Comores",
    indonesianName: "Komoro",
    icon: icons.Comoros,
    currencyCode: "KMF",
    currencySymbol: "CF",
    currencyName: "Comorian Franc",
  },
  COK: {
    id: "COK",
    name: "Cook Islands",
    nativeName: "Cook Islands",
    indonesianName: "Kepulauan Cook",
    icon: icons.CookIslands,
    currencyCode: "NZD",
    currencySymbol: "$",
    currencyName: "New Zealand Dollar",
  },
  COR: {
    id: "COR",
    name: "Corsica",
    nativeName: "Corse",
    indonesianName: "Korsika",
    icon: icons.Corsica,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  CRI: {
    id: "CRI",
    name: "Costa Rica",
    nativeName: "Costa Rica",
    indonesianName: "Kosta Rika",
    icon: icons.CostaRica,
    currencyCode: "CRC",
    currencySymbol: "₡",
    currencyName: "Costa Rican Colón",
  },
  HRV: {
    id: "HRV",
    name: "Croatia",
    nativeName: "Hrvatska",
    indonesianName: "Kroasia",
    icon: icons.Croatia,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  CUB: {
    id: "CUB",
    name: "Cuba",
    nativeName: "Cuba",
    indonesianName: "Kuba",
    icon: icons.Cuba,
    currencyCode: "CUP",
    currencySymbol: "$",
    currencyName: "Cuban Peso",
  },
  CUW: {
    id: "CUW",
    name: "Curacao",
    nativeName: "Curaçao",
    indonesianName: "Curaçao",
    icon: icons.Curacao,
    currencyCode: "ANG",
    currencySymbol: "ƒ",
    currencyName: "Netherlands Antillean Guilder",
  },
  CYP: {
    id: "CYP",
    name: "Cyprus",
    nativeName: "Κύπρος",
    indonesianName: "Siprus",
    icon: icons.Cyprus,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  CZE: {
    id: "CZE",
    name: "Czech Republic",
    nativeName: "Česká republika",
    indonesianName: "Republik Ceko",
    icon: icons.CzechRepublic,
    currencyCode: "CZK",
    currencySymbol: "Kč",
    currencyName: "Czech Koruna",
  },
  COD: {
    id: "COD",
    name: "Democratic Republic of Congo",
    nativeName: "République démocratique du Congo",
    indonesianName: "Republik Demokratik Kongo",
    icon: icons.DemocraticRepublicOfCongo,
    currencyCode: "CDF",
    currencySymbol: "FC",
    currencyName: "Congolese Franc",
  },
  DNK: {
    id: "DNK",
    name: "Denmark",
    nativeName: "Danmark",
    indonesianName: "Denmark",
    icon: icons.Denmark,
    currencyCode: "DKK",
    currencySymbol: "kr",
    currencyName: "Danish Krone",
  },
  DJI: {
    id: "DJI",
    name: "Djibouti",
    nativeName: "Djibouti",
    indonesianName: "Jibuti",
    icon: icons.Djibouti,
    currencyCode: "DJF",
    currencySymbol: "Fdj",
    currencyName: "Djiboutian Franc",
  },
  DMA: {
    id: "DMA",
    name: "Dominica",
    nativeName: "Dominica",
    indonesianName: "Dominika",
    icon: icons.Dominica,
    currencyCode: "XCD",
    currencySymbol: "$",
    currencyName: "East Caribbean Dollar",
  },
  DOM: {
    id: "DOM",
    name: "Dominican Republic",
    nativeName: "República Dominicana",
    indonesianName: "Republik Dominika",
    icon: icons.DominicanRepublic,
    currencyCode: "DOP",
    currencySymbol: "$",
    currencyName: "Dominican Peso",
  },
  TLS: {
    id: "TLS",
    name: "East Timor",
    nativeName: "Timor-Leste",
    indonesianName: "Timor Leste",
    icon: icons.EastTimor,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  ECU: {
    id: "ECU",
    name: "Ecuador",
    nativeName: "Ecuador",
    indonesianName: "Ekuador",
    icon: icons.Ecuador,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  EGY: {
    id: "EGY",
    name: "Egypt",
    nativeName: "مصر",
    indonesianName: "Mesir",
    icon: icons.Egypt,
    currencyCode: "EGP",
    currencySymbol: "£",
    currencyName: "Egyptian Pound",
  },
  ENG: {
    id: "ENG",
    name: "England",
    nativeName: "England",
    indonesianName: "Inggris",
    icon: icons.England,
    currencyCode: "GBP",
    currencySymbol: "£",
    currencyName: "Pound Sterling",
  },
  GNQ: {
    id: "GNQ",
    name: "Equatorial Guinea",
    nativeName: "Guinea Ecuatorial",
    indonesianName: "Guinea Khatulistiwa",
    icon: icons.EquatorialGuinea,
    currencyCode: "XAF",
    currencySymbol: "FCFA",
    currencyName: "Central African CFA Franc",
  },
  ERI: {
    id: "ERI",
    name: "Eritrea",
    nativeName: "ኤርትራ",
    indonesianName: "Eritrea",
    icon: icons.Eritrea,
    currencyCode: "ERN",
    currencySymbol: "Nfk",
    currencyName: "Nakfa",
  },
  EST: {
    id: "EST",
    name: "Estonia",
    nativeName: "Eesti",
    indonesianName: "Estonia",
    icon: icons.Estonia,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  ETH: {
    id: "ETH",
    name: "Ethiopia",
    nativeName: "ኢትዮጵያ",
    indonesianName: "Etiopia",
    icon: icons.Ethiopia,
    currencyCode: "ETB",
    currencySymbol: "Br",
    currencyName: "Ethiopian Birr",
  },
  EUN: {
    id: "EUN",
    name: "European Union",
    nativeName: "European Union",
    indonesianName: "Uni Eropa",
    icon: icons.EuropeanUnion,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  FLK: {
    id: "FLK",
    name: "Falkland Islands",
    nativeName: "Falkland Islands",
    indonesianName: "Kepulauan Falkland",
    icon: icons.FalklandIslands,
    currencyCode: "FKP",
    currencySymbol: "£",
    currencyName: "Falkland Islands Pound",
  },
  FRO: {
    id: "FRO",
    name: "Faroe Islands",
    nativeName: "Føroyar",
    indonesianName: "Kepulauan Faroe",
    icon: icons.FaroeIslands,
    currencyCode: "DKK",
    currencySymbol: "kr",
    currencyName: "Faroese Króna",
  },
  FJI: {
    id: "FJI",
    name: "Fiji",
    nativeName: "Fiji",
    indonesianName: "Fiji",
    icon: icons.Fiji,
    currencyCode: "FJD",
    currencySymbol: "$",
    currencyName: "Fijian Dollar",
  },
  FIN: {
    id: "FIN",
    name: "Finland",
    nativeName: "Suomi",
    indonesianName: "Finlandia",
    icon: icons.Finland,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  FRA: {
    id: "FRA",
    name: "France",
    nativeName: "France",
    indonesianName: "Prancis",
    icon: icons.France,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  PYF: {
    id: "PYF",
    name: "French Polynesia",
    nativeName: "Polynésie française",
    indonesianName: "Polinesia Prancis",
    icon: icons.FrenchPolynesia,
    currencyCode: "XPF",
    currencySymbol: "₣",
    currencyName: "CFP Franc",
  },
  GAB: {
    id: "GAB",
    name: "Gabon",
    nativeName: "Gabon",
    indonesianName: "Gabon",
    icon: icons.Gabon,
    currencyCode: "XAF",
    currencySymbol: "FCFA",
    currencyName: "Central African CFA Franc",
  },
  GAL: {
    id: "GAL",
    name: "Galapagos Islands",
    nativeName: "Galápagos",
    indonesianName: "Kepulauan Galapagos",
    icon: icons.GalapagosIslands,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  GMB: {
    id: "GMB",
    name: "Gambia",
    nativeName: "Gambia",
    indonesianName: "Gambia",
    icon: icons.Gambia,
    currencyCode: "GMD",
    currencySymbol: "D",
    currencyName: "Dalasi",
  },
  DEU: {
    id: "DEU",
    name: "Germany",
    nativeName: "Deutschland",
    indonesianName: "Jerman",
    icon: icons.Germany,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  GHA: {
    id: "GHA",
    name: "Ghana",
    nativeName: "Ghana",
    indonesianName: "Ghana",
    icon: icons.Ghana,
    currencyCode: "GHS",
    currencySymbol: "₵",
    currencyName: "Cedi",
  },
  GIB: {
    id: "GIB",
    name: "Gibraltar",
    nativeName: "Gibraltar",
    indonesianName: "Gibraltar",
    icon: icons.Gibraltar,
    currencyCode: "GIP",
    currencySymbol: "£",
    currencyName: "Gibraltar Pound",
  },
  GRC: {
    id: "GRC",
    name: "Greece",
    nativeName: "Ελλάδα",
    indonesianName: "Yunani",
    icon: icons.Greece,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  GRL: {
    id: "GRL",
    name: "Greenland",
    nativeName: "Kalaallit Nunaat",
    indonesianName: "Greenland",
    icon: icons.Greenland,
    currencyCode: "DKK",
    currencySymbol: "kr",
    currencyName: "Danish Krone",
  },
  GRD: {
    id: "GRD",
    name: "Grenada",
    nativeName: "Grenada",
    indonesianName: "Grenada",
    icon: icons.Grenada,
    currencyCode: "XCD",
    currencySymbol: "$",
    currencyName: "East Caribbean Dollar",
  },
  GUM: {
    id: "GUM",
    name: "Guam",
    nativeName: "Guam",
    indonesianName: "Guam",
    icon: icons.Guam,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  GTM: {
    id: "GTM",
    name: "Guatemala",
    nativeName: "Guatemala",
    indonesianName: "Guatemala",
    icon: icons.Guatemala,
    currencyCode: "GTQ",
    currencySymbol: "Q",
    currencyName: "Quetzal",
  },
  GGY: {
    id: "GGY",
    name: "Guernsey",
    nativeName: "Guernsey",
    indonesianName: "Guernsey",
    icon: icons.Guernsey,
    currencyCode: "GBP",
    currencySymbol: "£",
    currencyName: "Guernsey Pound",
  },
  GNB: {
    id: "GNB",
    name: "Guinea-Bissau",
    nativeName: "Guiné-Bissau",
    indonesianName: "Guinea-Bissau",
    icon: icons.GuineaBissau,
    currencyCode: "XOF",
    currencySymbol: "CFA",
    currencyName: "West African CFA Franc",
  },
  GIN: {
    id: "GIN",
    name: "Guinea",
    nativeName: "Guinée",
    indonesianName: "Guinea",
    icon: icons.Guinea,
    currencyCode: "GNF",
    currencySymbol: "FG",
    currencyName: "Guinean Franc",
  },
  GUY: {
    id: "GUY",
    name: "Guyana",
    nativeName: "Guyana",
    indonesianName: "Guyana",
    icon: icons.Guyana,
    currencyCode: "GYD",
    currencySymbol: "$",
    currencyName: "Guyanese Dollar",
  },
  HTI: {
    id: "HTI",
    name: "Haiti",
    nativeName: "Ayiti",
    indonesianName: "Haiti",
    icon: icons.Haiti,
    currencyCode: "HTG",
    currencySymbol: "G",
    currencyName: "Gourde",
  },
  HAW: {
    id: "HAW",
    name: "Hawaii",
    nativeName: "Hawaiʻi",
    indonesianName: "Hawaii",
    icon: icons.Hawaii,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  HND: {
    id: "HND",
    name: "Honduras",
    nativeName: "Honduras",
    indonesianName: "Honduras",
    icon: icons.Honduras,
    currencyCode: "HNL",
    currencySymbol: "L",
    currencyName: "Lempira",
  },
  HKG: {
    id: "HKG",
    name: "Hong Kong",
    nativeName: "香港",
    indonesianName: "Hong Kong",
    icon: icons.HongKong,
    currencyCode: "HKD",
    currencySymbol: "$",
    currencyName: "Hong Kong Dollar",
  },
  HUN: {
    id: "HUN",
    name: "Hungary",
    nativeName: "Magyarország",
    indonesianName: "Hungaria",
    icon: icons.Hungary,
    currencyCode: "HUF",
    currencySymbol: "Ft",
    currencyName: "Forint",
  },
  ISL: {
    id: "ISL",
    name: "Iceland",
    nativeName: "Ísland",
    indonesianName: "Islandia",
    icon: icons.Iceland,
    currencyCode: "ISK",
    currencySymbol: "kr",
    currencyName: "Icelandic Króna",
  },
  IND: {
    id: "IND",
    name: "India",
    nativeName: "भारत",
    indonesianName: "India",
    icon: icons.India,
    currencyCode: "INR",
    currencySymbol: "₹",
    currencyName: "Indian Rupee",
  },
  IDN: {
    id: "IDN",
    name: "Indonesia",
    nativeName: "Indonesia",
    indonesianName: "Indonesia",
    icon: icons.Indonesia,
    currencyCode: "IDR",
    currencySymbol: "Rp",
    currencyName: "Rupiah",
  },
  IRN: {
    id: "IRN",
    name: "Iran",
    nativeName: "ایران",
    indonesianName: "Iran",
    icon: icons.Iran,
    currencyCode: "IRR",
    currencySymbol: "﷼",
    currencyName: "Iranian Rial",
  },
  IRQ: {
    id: "IRQ",
    name: "Iraq",
    nativeName: "العراق",
    indonesianName: "Irak",
    icon: icons.Iraq,
    currencyCode: "IQD",
    currencySymbol: "ع.د",
    currencyName: "Iraqi Dinar",
  },
  IRL: {
    id: "IRL",
    name: "Ireland",
    nativeName: "Éire",
    indonesianName: "Irlandia",
    icon: icons.Ireland,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  IMN: {
    id: "IMN",
    name: "Isle of Man",
    nativeName: "Ellan Vannin",
    indonesianName: "Pulau Man",
    icon: icons.IsleOfMan,
    currencyCode: "IMP",
    currencySymbol: "£",
    currencyName: "Manx Pound",
  },
  ISR: {
    id: "ISR",
    name: "Israel",
    nativeName: "ישראל",
    indonesianName: "Israel",
    icon: icons.Israel,
    currencyCode: "ILS",
    currencySymbol: "₪",
    currencyName: "New Shekel",
  },
  ITA: {
    id: "ITA",
    name: "Italy",
    nativeName: "Italia",
    indonesianName: "Italia",
    icon: icons.Italy,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  CIV: {
    id: "CIV",
    name: "Ivory Coast",
    nativeName: "Côte d'Ivoire",
    indonesianName: "Pantai Gading",
    icon: icons.IvoryCoast,
    currencyCode: "XOF",
    currencySymbol: "CFA",
    currencyName: "West African CFA Franc",
  },
  JAM: {
    id: "JAM",
    name: "Jamaica",
    nativeName: "Jamaica",
    indonesianName: "Jamaika",
    icon: icons.Jamaica,
    currencyCode: "JMD",
    currencySymbol: "$",
    currencyName: "Jamaican Dollar",
  },
  JPN: {
    id: "JPN",
    name: "Japan",
    nativeName: "日本",
    indonesianName: "Jepang",
    icon: icons.Japan,
    currencyCode: "JPY",
    currencySymbol: "¥",
    currencyName: "Yen",
  },
  JEY: {
    id: "JEY",
    name: "Jersey",
    nativeName: "Jersey",
    indonesianName: "Jersey",
    icon: icons.Jersey,
    currencyCode: "JEP",
    currencySymbol: "£",
    currencyName: "Jersey Pound",
  },
  JOR: {
    id: "JOR",
    name: "Jordan",
    nativeName: "الأردن",
    indonesianName: "Yordania",
    icon: icons.Jordan,
    currencyCode: "JOD",
    currencySymbol: "د.أ",
    currencyName: "Jordanian Dinar",
  },
  KAZ: {
    id: "KAZ",
    name: "Kazakhstan",
    nativeName: "Қазақстан",
    indonesianName: "Kazakhstan",
    icon: icons.Kazakhstan,
    currencyCode: "KZT",
    currencySymbol: "₸",
    currencyName: "Tenge",
  },
  KEN: {
    id: "KEN",
    name: "Kenya",
    nativeName: "Kenya",
    indonesianName: "Kenya",
    icon: icons.Kenya,
    currencyCode: "KES",
    currencySymbol: "KSh",
    currencyName: "Kenyan Shilling",
  },
  KIR: {
    id: "KIR",
    name: "Kiribati",
    nativeName: "Kiribati",
    indonesianName: "Kiribati",
    icon: icons.Kiribati,
    currencyCode: "AUD",
    currencySymbol: "$",
    currencyName: "Australian Dollar",
  },
  RKS: {
    id: "RKS",
    name: "Kosovo",
    nativeName: "Kosova",
    indonesianName: "Kosovo",
    icon: icons.Kosovo,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  KWT: {
    id: "KWT",
    name: "Kuwait",
    nativeName: "الكويت",
    indonesianName: "Kuwait",
    icon: icons.Kuwait,
    currencyCode: "KWD",
    currencySymbol: "د.ك",
    currencyName: "Kuwaiti Dinar",
  },
  KGZ: {
    id: "KGZ",
    name: "Kyrgyzstan",
    nativeName: "Кыргызстан",
    indonesianName: "Kirgistan",
    icon: icons.Kyrgyzstan,
    currencyCode: "KGS",
    currencySymbol: "с",
    currencyName: "Som",
  },
  LAO: {
    id: "LAO",
    name: "Laos",
    nativeName: "ລາວ",
    indonesianName: "Laos",
    icon: icons.Laos,
    currencyCode: "LAK",
    currencySymbol: "₭",
    currencyName: "Kip",
  },
  LVA: {
    id: "LVA",
    name: "Latvia",
    nativeName: "Latvija",
    indonesianName: "Latvia",
    icon: icons.Latvia,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  LBN: {
    id: "LBN",
    name: "Lebanon",
    nativeName: "لبنان",
    indonesianName: "Lebanon",
    icon: icons.Lebanon,
    currencyCode: "LBP",
    currencySymbol: "ل.ل",
    currencyName: "Lebanese Pound",
  },
  LSO: {
    id: "LSO",
    name: "Lesotho",
    nativeName: "Lesotho",
    indonesianName: "Lesotho",
    icon: icons.Lesotho,
    currencyCode: "LSL",
    currencySymbol: "L",
    currencyName: "Loti",
  },
  LBR: {
    id: "LBR",
    name: "Liberia",
    nativeName: "Liberia",
    indonesianName: "Liberia",
    icon: icons.Liberia,
    currencyCode: "LRD",
    currencySymbol: "$",
    currencyName: "Liberian Dollar",
  },
  LBY: {
    id: "LBY",
    name: "Libya",
    nativeName: "ليبيا",
    indonesianName: "Libya",
    icon: icons.Libya,
    currencyCode: "LYD",
    currencySymbol: "ل.د",
    currencyName: "Libyan Dinar",
  },
  LIE: {
    id: "LIE",
    name: "Liechtenstein",
    nativeName: "Liechtenstein",
    indonesianName: "Liechtenstein",
    icon: icons.Liechtenstein,
    currencyCode: "CHF",
    currencySymbol: "Fr",
    currencyName: "Swiss Franc",
  },
  LTU: {
    id: "LTU",
    name: "Lithuania",
    nativeName: "Lietuva",
    indonesianName: "Lituania",
    icon: icons.Lithuania,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  MAC: {
    id: "MAC",
    name: "Macao",
    nativeName: "澳門",
    indonesianName: "Makau",
    icon: icons.Macao,
    currencyCode: "MOP",
    currencySymbol: "P",
    currencyName: "Pataca",
  },
  MDG: {
    id: "MDG",
    name: "Madagascar",
    nativeName: "Madagasikara",
    indonesianName: "Madagaskar",
    icon: icons.Madagascar,
    currencyCode: "MGA",
    currencySymbol: "Ar",
    currencyName: "Ariary",
  },
  MAD: {
    id: "MAD",
    name: "Madeira",
    nativeName: "Madeira",
    indonesianName: "Madeira",
    icon: icons.Madeira,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  MWI: {
    id: "MWI",
    name: "Malawi",
    nativeName: "Malawi",
    indonesianName: "Malawi",
    icon: icons.Malawi,
    currencyCode: "MWK",
    currencySymbol: "MK",
    currencyName: "Kwacha",
  },
  MYS: {
    id: "MYS",
    name: "Malaysia",
    nativeName: "Malaysia",
    indonesianName: "Malaysia",
    icon: icons.Malaysia,
    currencyCode: "MYR",
    currencySymbol: "RM",
    currencyName: "Ringgit",
  },
  MDV: {
    id: "MDV",
    name: "Maldives",
    nativeName: "ދިވެހިރާއްޖެ",
    indonesianName: "Maladewa",
    icon: icons.Maldives,
    currencyCode: "MVR",
    currencySymbol: ".ރ",
    currencyName: "Rufiyaa",
  },
  MLI: {
    id: "MLI",
    name: "Mali",
    nativeName: "Mali",
    indonesianName: "Mali",
    icon: icons.Mali,
    currencyCode: "XOF",
    currencySymbol: "CFA",
    currencyName: "West African CFA Franc",
  },
  MLT: {
    id: "MLT",
    name: "Malta",
    nativeName: "Malta",
    indonesianName: "Malta",
    icon: icons.Malta,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  MHL: {
    id: "MHL",
    name: "Marshall Island",
    nativeName: "Aorōkin M̧ajeļ",
    indonesianName: "Kepulauan Marshall",
    icon: icons.MarshallIsland,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  MTQ: {
    id: "MTQ",
    name: "Martinique",
    nativeName: "Martinique",
    indonesianName: "Martinik",
    icon: icons.Martinique,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  MRT: {
    id: "MRT",
    name: "Mauritania",
    nativeName: "موريتانيا",
    indonesianName: "Mauritania",
    icon: icons.Mauritania,
    currencyCode: "MRU",
    currencySymbol: "UM",
    currencyName: "Ouguiya",
  },
  MUS: {
    id: "MUS",
    name: "Mauritius",
    nativeName: "Mauritius",
    indonesianName: "Mauritius",
    icon: icons.Mauritius,
    currencyCode: "MUR",
    currencySymbol: "₨",
    currencyName: "Mauritian Rupee",
  },
  MEL: {
    id: "MEL",
    name: "Melilla",
    nativeName: "Melilla",
    indonesianName: "Melilla",
    icon: icons.Melilla,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  MEX: {
    id: "MEX",
    name: "Mexico",
    nativeName: "México",
    indonesianName: "Meksiko",
    icon: icons.Mexico,
    currencyCode: "MXN",
    currencySymbol: "$",
    currencyName: "Mexican Peso",
  },
  FSM: {
    id: "FSM",
    name: "Micronesia",
    nativeName: "Micronesia",
    indonesianName: "Mikronesia",
    icon: icons.Micronesia,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  MDA: {
    id: "MDA",
    name: "Moldova",
    nativeName: "Moldova",
    indonesianName: "Moldova",
    icon: icons.Moldova,
    currencyCode: "MDL",
    currencySymbol: "L",
    currencyName: "Moldovan Leu",
  },
  MCO: {
    id: "MCO",
    name: "Monaco",
    nativeName: "Monaco",
    indonesianName: "Monako",
    icon: icons.Monaco,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  MNG: {
    id: "MNG",
    name: "Mongolia",
    nativeName: "Монгол улс",
    indonesianName: "Mongolia",
    icon: icons.Mongolia,
    currencyCode: "MNT",
    currencySymbol: "₮",
    currencyName: "Tögrög",
  },
  MNE: {
    id: "MNE",
    name: "Montenegro",
    nativeName: "Crna Gora",
    indonesianName: "Montenegro",
    icon: icons.Montenegro,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  MSR: {
    id: "MSR",
    name: "Montserrat",
    nativeName: "Montserrat",
    indonesianName: "Montserrat",
    icon: icons.Montserrat,
    currencyCode: "XCD",
    currencySymbol: "$",
    currencyName: "East Caribbean Dollar",
  },
  MAR: {
    id: "MAR",
    name: "Morocco",
    nativeName: "المغرب",
    indonesianName: "Maroko",
    icon: icons.Morocco,
    currencyCode: "MAD",
    currencySymbol: "د.م.",
    currencyName: "Moroccan Dirham",
  },
  MOZ: {
    id: "MOZ",
    name: "Mozambique",
    nativeName: "Moçambique",
    indonesianName: "Mozambik",
    icon: icons.Mozambique,
    currencyCode: "MZN",
    currencySymbol: "MT",
    currencyName: "Metical",
  },
  MMR: {
    id: "MMR",
    name: "Myanmar",
    nativeName: "မြန်မာ",
    indonesianName: "Myanmar",
    icon: icons.Myanmar,
    currencyCode: "MMK",
    currencySymbol: "K",
    currencyName: "Kyat",
  },
  NAM: {
    id: "NAM",
    name: "Namibia",
    nativeName: "Namibia",
    indonesianName: "Namibia",
    icon: icons.Namibia,
    currencyCode: "NAD",
    currencySymbol: "$",
    currencyName: "Namibian Dollar",
  },
  NATO: {
    id: "NATO",
    name: "Nato",
    nativeName: "NATO",
    indonesianName: "NATO",
    icon: icons.Nato,
    currencyCode: '',
    currencySymbol: '',
    currencyName: '',
  },
  NRU: {
    id: "NRU",
    name: "Nauru",
    nativeName: "Naoero",
    indonesianName: "Nauru",
    icon: icons.Nauru,
    currencyCode: "AUD",
    currencySymbol: "$",
    currencyName: "Australian Dollar",
  },
  NPL: {
    id: "NPL",
    name: "Nepal",
    nativeName: "नेपाल",
    indonesianName: "Nepal",
    icon: icons.Nepal,
    currencyCode: "NPR",
    currencySymbol: "₨",
    currencyName: "Nepalese Rupee",
  },
  NLD: {
    id: "NLD",
    name: "Netherlands",
    nativeName: "Nederland",
    indonesianName: "Belanda",
    icon: icons.Netherlands,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  NZL: {
    id: "NZL",
    name: "New Zealand",
    nativeName: "Aotearoa",
    indonesianName: "Selandia Baru",
    icon: icons.NewZealand,
    currencyCode: "NZD",
    currencySymbol: "$",
    currencyName: "New Zealand Dollar",
  },
  NIC: {
    id: "NIC",
    name: "Nicaragua",
    nativeName: "Nicaragua",
    indonesianName: "Nikaragua",
    icon: icons.Nicaragua,
    currencyCode: "NIO",
    currencySymbol: "C$",
    currencyName: "Córdoba",
  },
  NER: {
    id: "NER",
    name: "Niger",
    nativeName: "Niger",
    indonesianName: "Niger",
    icon: icons.Niger,
    currencyCode: "XOF",
    currencySymbol: "CFA",
    currencyName: "West African CFA Franc",
  },
  NGA: {
    id: "NGA",
    name: "Nigeria",
    nativeName: "Nigeria",
    indonesianName: "Nigeria",
    icon: icons.Nigeria,
    currencyCode: "NGN",
    currencySymbol: "₦",
    currencyName: "Naira",
  },
  NIU: {
    id: "NIU",
    name: "Niue",
    nativeName: "Niuē",
    indonesianName: "Niue",
    icon: icons.Niue,
    currencyCode: "NZD",
    currencySymbol: "$",
    currencyName: "New Zealand Dollar",
  },
  NFK: {
    id: "NFK",
    name: "Norfolk Island",
    nativeName: "Norfolk Island",
    indonesianName: "Pulau Norfolk",
    icon: icons.NorfolkIsland,
    currencyCode: "AUD",
    currencySymbol: "$",
    currencyName: "Australian Dollar",
  },
  PRK: {
    id: "PRK",
    name: "North Korea",
    nativeName: "조선",
    indonesianName: "Korea Utara",
    icon: icons.NorthKorea,
    currencyCode: "KPW",
    currencySymbol: "₩",
    currencyName: "North Korean Won",
  },
  TRNC: {
    id: "TRNC",
    name: "Northern Cyprus",
    nativeName: "Kuzey Kıbrıs",
    indonesianName: "Siprus Utara",
    icon: icons.NorthenCyprus,
    currencyCode: "TRY",
    currencySymbol: "₺",
    currencyName: "Turkish Lira",
  },
  MNP: {
    id: "MNP",
    name: "Northern Marianas Islands",
    nativeName: "Northern Mariana Islands",
    indonesianName: "Kepulauan Mariana Utara",
    icon: icons.NorthernMarianasIslands,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  NOR: {
    id: "NOR",
    name: "Norway",
    nativeName: "Norge",
    indonesianName: "Norwegia",
    icon: icons.Norway,
    currencyCode: "NOK",
    currencySymbol: "kr",
    currencyName: "Norwegian Krone",
  },
  OMN: {
    id: "OMN",
    name: "Oman",
    nativeName: "عُمان",
    indonesianName: "Oman",
    icon: icons.Oman,
    currencyCode: "OMR",
    currencySymbol: "﷼",
    currencyName: "Omani Rial",
  },
  ORK: {
    id: "ORK",
    name: "Orkney Islands",
    nativeName: "Orkney",
    indonesianName: "Kepulauan Orkney",
    icon: icons.OrkneyIslands,
    currencyCode: "GBP",
    currencySymbol: "£",
    currencyName: "Pound Sterling",
  },
  OSS: {
    id: "OSS",
    name: "Ossetia",
    nativeName: "Ирыстон",
    indonesianName: "Ossetia",
    icon: icons.Ossetia,
    currencyCode: "RUB",
    currencySymbol: "₽",
    currencyName: "Ruble",
  },
  PAK: {
    id: "PAK",
    name: "Pakistan",
    nativeName: "پاکستان",
    indonesianName: "Pakistan",
    icon: icons.Pakistan,
    currencyCode: "PKR",
    currencySymbol: "₨",
    currencyName: "Pakistani Rupee",
  },
  PLW: {
    id: "PLW",
    name: "Palau",
    nativeName: "Belau",
    indonesianName: "Palau",
    icon: icons.Palau,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  PSE: {
    id: "PSE",
    name: "Palestine",
    nativeName: "فلسطين",
    indonesianName: "Palestina",
    icon: icons.Palestine,
    currencyCode: "ILS",
    currencySymbol: "₪",
    currencyName: "New Shekel",
  },
  PAN: {
    id: "PAN",
    name: "Panama",
    nativeName: "Panamá",
    indonesianName: "Panama",
    icon: icons.Panama,
    currencyCode: "PAB",
    currencySymbol: "B/.",
    currencyName: "Balboa",
  },
  PNG: {
    id: "PNG",
    name: "Papua New Guinea",
    nativeName: "Papua Niugini",
    indonesianName: "Papua Nugini",
    icon: icons.PapuaNewGuinea,
    currencyCode: "PGK",
    currencySymbol: "K",
    currencyName: "Kina",
  },
  PRY: {
    id: "PRY",
    name: "Paraguay",
    nativeName: "Paraguay",
    indonesianName: "Paraguay",
    icon: icons.Paraguay,
    currencyCode: "PYG",
    currencySymbol: "₲",
    currencyName: "Guaraní",
  },
  PER: {
    id: "PER",
    name: "Peru",
    nativeName: "Perú",
    indonesianName: "Peru",
    icon: icons.Peru,
    currencyCode: "PEN",
    currencySymbol: "S/.",
    currencyName: "Sol",
  },
  PHL: {
    id: "PHL",
    name: "Philippines",
    nativeName: "Pilipinas",
    indonesianName: "Filipina",
    icon: icons.Philippines,
    currencyCode: "PHP",
    currencySymbol: "₱",
    currencyName: "Philippine Peso",
  },
  PCN: {
    id: "PCN",
    name: "Pitcairn Islands",
    nativeName: "Pitcairn Islands",
    indonesianName: "Kepulauan Pitcairn",
    icon: icons.PitcairnIslands,
    currencyCode: "NZD",
    currencySymbol: "$",
    currencyName: "New Zealand Dollar",
  },
  PRT: {
    id: "PRT",
    name: "Portugal",
    nativeName: "Portugal",
    indonesianName: "Portugal",
    icon: icons.Portugal,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  PRI: {
    id: "PRI",
    name: "Puerto Rico",
    nativeName: "Puerto Rico",
    indonesianName: "Puerto Riko",
    icon: icons.PuertoRico,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  QAT: {
    id: "QAT",
    name: "Qatar",
    nativeName: "قطر",
    indonesianName: "Qatar",
    icon: icons.Qatar,
    currencyCode: "QAR",
    currencySymbol: "﷼",
    currencyName: "Qatari Riyal",
  },
  RAP: {
    id: "RAP",
    name: "Rapa Nui",
    nativeName: "Rapa Nui",
    indonesianName: "Pulau Paskah",
    icon: icons.RapaNui,
    currencyCode: "CLP",
    currencySymbol: "$",
    currencyName: "Chilean Peso",
  },
  MKD: {
    id: "MKD",
    name: "Republic of Macedonia",
    nativeName: "Македонија",
    indonesianName: "Makedonia Utara",
    icon: icons.RepublicOfMacedonia,
    currencyCode: "MKD",
    currencySymbol: "ден",
    currencyName: "Denar",
  },
  POL: {
    id: "POL",
    name: "Republic of Poland",
    nativeName: "Polska",
    indonesianName: "Polandia",
    icon: icons.RepublicOfPoland,
    currencyCode: "PLN",
    currencySymbol: "zł",
    currencyName: "Złoty",
  },
  COG: {
    id: "COG",
    name: "Republic of the Congo",
    nativeName: "République du Congo",
    indonesianName: "Republik Kongo",
    icon: icons.RepublicOfTheCongo,
    currencyCode: "XAF",
    currencySymbol: "FCFA",
    currencyName: "Central African CFA Franc",
  },
  ROU: {
    id: "ROU",
    name: "Romania",
    nativeName: "România",
    indonesianName: "Rumania",
    icon: icons.Romania,
    currencyCode: "RON",
    currencySymbol: "L",
    currencyName: "Romanian Leu",
  },
  RUS: {
    id: "RUS",
    name: "Russia",
    nativeName: "Россия",
    indonesianName: "Rusia",
    icon: icons.Russia,
    currencyCode: "RUB",
    currencySymbol: "₽",
    currencyName: "Ruble",
  },
  RWA: {
    id: "RWA",
    name: "Rwanda",
    nativeName: "Rwanda",
    indonesianName: "Rwanda",
    icon: icons.Rwanda,
    currencyCode: "RWF",
    currencySymbol: "FRw",
    currencyName: "Rwandan Franc",
  },
  SAB: {
    id: "SAB",
    name: "Saba Island",
    nativeName: "Saba",
    indonesianName: "Pulau Saba",
    icon: icons.SabaIsland,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  KNA: {
    id: "KNA",
    name: "Saint Kitts and Nevis",
    nativeName: "Saint Kitts and Nevis",
    indonesianName: "Saint Kitts dan Nevis",
    icon: icons.SaintKittsAndNevis,
    currencyCode: "XCD",
    currencySymbol: "$",
    currencyName: "East Caribbean Dollar",
  },
  SLV: {
    id: "SLV",
    name: "Salvador",
    nativeName: "El Salvador",
    indonesianName: "El Salvador",
    icon: icons.Salvador,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  WSM: {
    id: "WSM",
    name: "Samoa",
    nativeName: "Samoa",
    indonesianName: "Samoa",
    icon: icons.Samoa,
    currencyCode: "WST",
    currencySymbol: "T",
    currencyName: "Tālā",
  },
  SMR: {
    id: "SMR",
    name: "San Marino",
    nativeName: "San Marino",
    indonesianName: "San Marino",
    icon: icons.SanMarino,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  STP: {
    id: "STP",
    name: "Sao Tome and Principe",
    nativeName: "São Tomé e Príncipe",
    indonesianName: "Sao Tome dan Principe",
    icon: icons.SaoTomeAndPrincipe,
    currencyCode: "STN",
    currencySymbol: "Db",
    currencyName: "Dobra",
  },
  SARD: {
    id: "SARD",
    name: "Sardinia",
    nativeName: "Sardegna",
    indonesianName: "Sardinia",
    icon: icons.Sardinia,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  SAU: {
    id: "SAU",
    name: "Saudi Arabia",
    nativeName: "العربية السعودية",
    indonesianName: "Arab Saudi",
    icon: icons.SaudiArabia,
    currencyCode: "SAR",
    currencySymbol: "﷼",
    currencyName: "Saudi Riyal",
  },
  SCO: {
    id: "SCO",
    name: "Scotland",
    nativeName: "Scotland",
    indonesianName: "Skotlandia",
    icon: icons.Scotland,
    currencyCode: "GBP",
    currencySymbol: "£",
    currencyName: "Pound Sterling",
  },
  SEN: {
    id: "SEN",
    name: "Senegal",
    nativeName: "Sénégal",
    indonesianName: "Senegal",
    icon: icons.Senegal,
    currencyCode: "XOF",
    currencySymbol: "CFA",
    currencyName: "West African CFA Franc",
  },
  SRB: {
    id: "SRB",
    name: "Serbia",
    nativeName: "Србија",
    indonesianName: "Serbia",
    icon: icons.Serbia,
    currencyCode: "RSD",
    currencySymbol: "дин.",
    currencyName: "Serbian Dinar",
  },
  SYC: {
    id: "SYC",
    name: "Seychelles",
    nativeName: "Seychelles",
    indonesianName: "Seychelles",
    icon: icons.Seychelles,
    currencyCode: "SCR",
    currencySymbol: "₨",
    currencyName: "Seychellois Rupee",
  },
  SLE: {
    id: "SLE",
    name: "Sierra Leone",
    nativeName: "Sierra Leone",
    indonesianName: "Sierra Leone",
    icon: icons.SierraLeone,
    currencyCode: "SLE",
    currencySymbol: "Le",
    currencyName: "Leone",
  },
  SGP: {
    id: "SGP",
    name: "Singapore",
    nativeName: "Singapore",
    indonesianName: "Singapura",
    icon: icons.Singapore,
    currencyCode: "SGD",
    currencySymbol: "$",
    currencyName: "Singapore Dollar",
  },
  SXE: {
    id: "SXE",
    name: "Sint Eustatius",
    nativeName: "Sint Eustatius",
    indonesianName: "Sint Eustatius",
    icon: icons.SintEustatius,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  SXM: {
    id: "SXM",
    name: "Sint Maarten",
    nativeName: "Sint Maarten",
    indonesianName: "Sint Maarten",
    icon: icons.SintMaarten,
    currencyCode: "ANG",
    currencySymbol: "ƒ",
    currencyName: "Netherlands Antillean Guilder",
  },
  SVK: {
    id: "SVK",
    name: "Slovakia",
    nativeName: "Slovensko",
    indonesianName: "Slovakia",
    icon: icons.Slovakia,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  SVN: {
    id: "SVN",
    name: "Slovenia",
    nativeName: "Slovenija",
    indonesianName: "Slovenia",
    icon: icons.Slovenia,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  SLB: {
    id: "SLB",
    name: "Solomon Islands",
    nativeName: "Solomon Islands",
    indonesianName: "Kepulauan Solomon",
    icon: icons.SolomonIslands,
    currencyCode: "SBD",
    currencySymbol: "$",
    currencyName: "Solomon Islands Dollar",
  },
  SOM: {
    id: "SOM",
    name: "Somalia",
    nativeName: "Soomaaliya",
    indonesianName: "Somalia",
    icon: icons.Somalia,
    currencyCode: "SOS",
    currencySymbol: "S",
    currencyName: "Somali Shilling",
  },
  SML: {
    id: "SML",
    name: "Somaliland",
    nativeName: "Somaliland",
    indonesianName: "Somaliland",
    icon: icons.Somaliland,
    currencyCode: "SLSH",
    currencySymbol: "Sl",
    currencyName: "Somaliland Shilling",
  },
  ZAF: {
    id: "ZAF",
    name: "South Africa",
    nativeName: "South Africa",
    indonesianName: "Afrika Selatan",
    icon: icons.SouthAfrica,
    currencyCode: "ZAR",
    currencySymbol: "R",
    currencyName: "Rand",
  },
  KOR: {
    id: "KOR",
    name: "South Korea",
    nativeName: "대한민국",
    indonesianName: "Korea Selatan",
    icon: icons.SouthKorea,
    currencyCode: "KRW",
    currencySymbol: "₩",
    currencyName: "South Korean Won",
  },
  SSD: {
    id: "SSD",
    name: "South Sudan",
    nativeName: "South Sudan",
    indonesianName: "Sudan Selatan",
    icon: icons.SouthSudan,
    currencyCode: "SSP",
    currencySymbol: "£",
    currencyName: "South Sudanese Pound",
  },
  ESP: {
    id: "ESP",
    name: "Spain",
    nativeName: "España",
    indonesianName: "Spanyol",
    icon: icons.Spain,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  LKA: {
    id: "LKA",
    name: "Sri Lanka",
    nativeName: "ශ්‍රී ලංකාව",
    indonesianName: "Sri Lanka",
    icon: icons.SriLanka,
    currencyCode: "LKR",
    currencySymbol: "₨",
    currencyName: "Sri Lankan Rupee",
  },
  BLM: {
    id: "BLM",
    name: "St. Barts",
    nativeName: "Saint-Barthélemy",
    indonesianName: "Saint Barthélemy",
    icon: icons.StBarts,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  LCA: {
    id: "LCA",
    name: "St. Lucia",
    nativeName: "Saint Lucia",
    indonesianName: "Saint Lucia",
    icon: icons.StLucia,
    currencyCode: "XCD",
    currencySymbol: "$",
    currencyName: "East Caribbean Dollar",
  },
  VCT: {
    id: "VCT",
    name: "St. Vincent and the Grenadines",
    nativeName: "Saint Vincent and the Grenadines",
    indonesianName: "Saint Vincent dan Grenadine",
    icon: icons.StVincentAndTheGrenadines,
    currencyCode: "XCD",
    currencySymbol: "$",
    currencyName: "East Caribbean Dollar",
  },
  SDN: {
    id: "SDN",
    name: "Sudan",
    nativeName: "السودان",
    indonesianName: "Sudan",
    icon: icons.Sudan,
    currencyCode: "SDG",
    currencySymbol: "ج.س.",
    currencyName: "Sudanese Pound",
  },
  SUR: {
    id: "SUR",
    name: "Suriname",
    nativeName: "Suriname",
    indonesianName: "Suriname",
    icon: icons.Suriname,
    currencyCode: "SRD",
    currencySymbol: "$",
    currencyName: "Surinamese Dollar",
  },
  SWZ: {
    id: "SWZ",
    name: "Eswatini",
    nativeName: "eSwatini",
    indonesianName: "Eswatini",
    icon: icons.Swaziland,
    currencyCode: "SZL",
    currencySymbol: "L",
    currencyName: "Lilangeni",
  },
  SWE: {
    id: "SWE",
    name: "Sweden",
    nativeName: "Sverige",
    indonesianName: "Swedia",
    icon: icons.Sweden,
    currencyCode: "SEK",
    currencySymbol: "kr",
    currencyName: "Swedish Krona",
  },
  CHE: {
    id: "CHE",
    name: "Switzerland",
    nativeName: "Schweiz",
    indonesianName: "Swiss",
    icon: icons.Switzerland,
    currencyCode: "CHF",
    currencySymbol: "Fr",
    currencyName: "Swiss Franc",
  },
  SYR: {
    id: "SYR",
    name: "Syria",
    nativeName: "سوريا",
    indonesianName: "Suriah",
    icon: icons.Syria,
    currencyCode: "SYP",
    currencySymbol: "£",
    currencyName: "Syrian Pound",
  },
  TWN: {
    id: "TWN",
    name: "Taiwan",
    nativeName: "臺灣",
    indonesianName: "Taiwan",
    icon: icons.Taiwan,
    currencyCode: "TWD",
    currencySymbol: "$",
    currencyName: "New Taiwan Dollar",
  },
  TJK: {
    id: "TJK",
    name: "Tajikistan",
    nativeName: "Тоҷикистон",
    indonesianName: "Tajikistan",
    icon: icons.Tajikistan,
    currencyCode: "TJS",
    currencySymbol: "SM",
    currencyName: "Somoni",
  },
  TZA: {
    id: "TZA",
    name: "Tanzania",
    nativeName: "Tanzania",
    indonesianName: "Tanzania",
    icon: icons.Tanzania,
    currencyCode: "TZS",
    currencySymbol: "Sh",
    currencyName: "Tanzanian Shilling",
  },
  THA: {
    id: "THA",
    name: "Thailand",
    nativeName: "ประเทศไทย",
    indonesianName: "Thailand",
    icon: icons.Thailand,
    currencyCode: "THB",
    currencySymbol: "฿",
    currencyName: "Baht",
  },
  TIB: {
    id: "TIB",
    name: "Tibet",
    nativeName: "བོད་",
    indonesianName: "Tibet",
    icon: icons.Tibet,
    currencyCode: "CNY",
    currencySymbol: "¥",
    currencyName: "Yuan",
  },
  TGO: {
    id: "TGO",
    name: "Togo",
    nativeName: "Togo",
    indonesianName: "Togo",
    icon: icons.Togo,
    currencyCode: "XOF",
    currencySymbol: "CFA",
    currencyName: "West African CFA Franc",
  },
  TKL: {
    id: "TKL",
    name: "Tokelau",
    nativeName: "Tokelau",
    indonesianName: "Tokelau",
    icon: icons.Tokelau,
    currencyCode: "NZD",
    currencySymbol: "$",
    currencyName: "New Zealand Dollar",
  },
  TON: {
    id: "TON",
    name: "Tonga",
    nativeName: "Tonga",
    indonesianName: "Tonga",
    icon: icons.Tonga,
    currencyCode: "TOP",
    currencySymbol: "T$",
    currencyName: "Paʻanga",
  },
  TRA: {
    id: "TRA",
    name: "Transnistria",
    nativeName: "Приднестровье",
    indonesianName: "Transnistria",
    icon: icons.Transnistria,
    currencyCode: "PRB",
    currencySymbol: "р.",
    currencyName: "Transnistrian Ruble",
  },
  TTO: {
    id: "TTO",
    name: "Trinidad and Tobago",
    nativeName: "Trinidad and Tobago",
    indonesianName: "Trinidad dan Tobago",
    icon: icons.TrinidadAndTobago,
    currencyCode: "TTD",
    currencySymbol: "$",
    currencyName: "Trinidad and Tobago Dollar",
  },
  TUN: {
    id: "TUN",
    name: "Tunisia",
    nativeName: "تونس",
    indonesianName: "Tunisia",
    icon: icons.Tunisia,
    currencyCode: "TND",
    currencySymbol: "د.ت",
    currencyName: "Tunisian Dinar",
  },
  TUR: {
    id: "TUR",
    name: "Turkey",
    nativeName: "Türkiye",
    indonesianName: "Turki",
    icon: icons.Turkey,
    currencyCode: "TRY",
    currencySymbol: "₺",
    currencyName: "Turkish Lira",
  },
  TKM: {
    id: "TKM",
    name: "Turkmenistan",
    nativeName: "Türkmenistan",
    indonesianName: "Turkmenistan",
    icon: icons.Turkmenistan,
    currencyCode: "TMT",
    currencySymbol: "m",
    currencyName: "Turkmenistan Manat",
  },
  TCA: {
    id: "TCA",
    name: "Turks and Caicos",
    nativeName: "Turks and Caicos Islands",
    indonesianName: "Turks dan Caicos",
    icon: icons.TurksAndCaicos,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  TUV: {
    id: "TUV",
    name: "Tuvalu",
    nativeName: "Tuvalu",
    indonesianName: "Tuvalu",
    icon: icons.Tuvalu,
    currencyCode: "AUD",
    currencySymbol: "$",
    currencyName: "Australian Dollar",
  },
  UGA: {
    id: "UGA",
    name: "Uganda",
    nativeName: "Uganda",
    indonesianName: "Uganda",
    icon: icons.Uganda,
    currencyCode: "UGX",
    currencySymbol: "USh",
    currencyName: "Ugandan Shilling",
  },
  UKR: {
    id: "UKR",
    name: "Ukraine",
    nativeName: "Україна",
    indonesianName: "Ukraina",
    icon: icons.Ukraine,
    currencyCode: "UAH",
    currencySymbol: "₴",
    currencyName: "Hryvnia",
  },
  ARE: {
    id: "ARE",
    name: "United Arab Emirates",
    nativeName: "الإمارات العربية المتحدة",
    indonesianName: "Uni Emirat Arab",
    icon: icons.UnitedArabEmirates,
    currencyCode: "AED",
    currencySymbol: "د.إ",
    currencyName: "UAE Dirham",
  },
  GBR: {
    id: "GBR",
    name: "United Kingdom",
    nativeName: "United Kingdom",
    indonesianName: "Britania Raya",
    icon: icons.UnitedKingdom,
    currencyCode: "GBP",
    currencySymbol: "£",
    currencyName: "Pound Sterling",
  },
  USA: {
    id: "USA",
    name: "United States of America",
    nativeName: "United States",
    indonesianName: "Amerika Serikat",
    icon: icons.UnitedStatesOfAmerica,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  URY: {
    id: "URY",
    name: "Uruguay",
    nativeName: "Uruguay",
    indonesianName: "Uruguay",
    icon: icons.Uruguay,
    currencyCode: "UYU",
    currencySymbol: "$",
    currencyName: "Uruguayan Peso",
  },
  UZB: {
    id: "UZB",
    name: "Uzbekistan",
    nativeName: "O‘zbekiston",
    indonesianName: "Uzbekistan",
    icon: icons.Uzbekistn,
    currencyCode: "UZS",
    currencySymbol: "soʻm",
    currencyName: "Uzbekistan Som",
  },
  VUT: {
    id: "VUT",
    name: "Vanuatu",
    nativeName: "Vanuatu",
    indonesianName: "Vanuatu",
    icon: icons.Vanuatu,
    currencyCode: "VUV",
    currencySymbol: "VT",
    currencyName: "Vatu",
  },
  VAT: {
    id: "VAT",
    name: "Vatican City",
    nativeName: "Civitas Vaticana",
    indonesianName: "Kota Vatikan",
    icon: icons.VaticanCity,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
  },
  VEN: {
    id: "VEN",
    name: "Venezuela",
    nativeName: "Venezuela",
    indonesianName: "Venezuela",
    icon: icons.Venezuela,
    currencyCode: "VES",
    currencySymbol: "Bs.",
    currencyName: "Bolívar Soberano",
  },
  VNM: {
    id: "VNM",
    name: "Vietnam",
    nativeName: "Việt Nam",
    indonesianName: "Vietnam",
    icon: icons.Vietnam,
    currencyCode: "VND",
    currencySymbol: "₫",
    currencyName: "Đồng",
  },
  VIR: {
    id: "VIR",
    name: "Virgin Islands",
    nativeName: "Virgin Islands",
    indonesianName: "Kepulauan Virgin Amerika Serikat",
    icon: icons.VirginIslands,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "United States Dollar",
  },
  WAL: {
    id: "WAL",
    name: "Wales",
    nativeName: "Cymru",
    indonesianName: "Wales",
    icon: icons.Wales,
    currencyCode: "GBP",
    currencySymbol: "£",
    currencyName: "Pound Sterling",
  },
  ESH: {
    id: "ESH",
    name: "Western Sahara",
    nativeName: "الصحراء الغربية",
    indonesianName: "Sahara Barat",
    icon: icons.WesternSahara,
    currencyCode: "MAD",
    currencySymbol: "د.م.",
    currencyName: "Moroccan Dirham",
  },
  YEM: {
    id: "YEM",
    name: "Yemen",
    nativeName: "اليمن",
    indonesianName: "Yaman",
    icon: icons.Yemen,
    currencyCode: "YER",
    currencySymbol: "﷼",
    currencyName: "Yemeni Rial",
  },
  ZMB: {
    id: "ZMB",
    name: "Zambia",
    nativeName: "Zambia",
    indonesianName: "Zambia",
    icon: icons.Zambia,
    currencyCode: "ZMW",
    currencySymbol: "K",
    currencyName: "Zambian Kwacha",
  },
  ZWE: {
    id: "ZWE",
    name: "Zimbabwe",
    nativeName: "Zimbabwe",
    indonesianName: "Zimbabwe",
    icon: icons.Zimbabwe,
    currencyCode: "ZWG",
    currencySymbol: "ZiG",
    currencyName: "Zimbabwe Gold",
  },
};`;

const raw = input;

const regex = /([A-Z]{3})\s*:\s*\{([\s\S]*?)\},/g;

const generationConfig = {
  responseMimeType: "application/json",
  responseSchema: schemaOutput,
};

const systemInstruction = `
Reformat the input country data to strictly follow the provided JSON schema.
Follow input structure and field names exactly.
Search using search google features to fill new fields.
Calling code example: '+62' for Indonesia.
iso2 must follow ISO 3166-1 alpha-2 standard, if not found, set as null.
numericCode must follow ISO 3166-1 numeric standard, if not found, set as null.
timezons example: ["Asia/Jakarta", "Asia/Makassar", "Asia/Jayapura"].
Must respond with only the JSON content without any additional text or explanation.
Example Data Output:
"IDN": {
  "id": "IDN",
  "name": "Indonesia",
  "nativeName": "Indonesia",
  "indonesianName": "Indonesia",
  "icon": icons.Indonesia,
  "currencyCode": "IDR",
  "currencySymbol": "Rp",
  "currencyName": "Rupiah",
  "emojiFlag": "🇮🇩",
  "continent": "Asia",
  "subregion": "South-Eastern Asia",
  "callingCode": "+62",
  "languages": [
    "id"
  ],
  "currencyDecimals": 2,
  "iso2": "ID",
  "iso3": "IDN",
  "numericCode": "360",
  "timezones": [
    "Asia/Jakarta",
    "Asia/Pontianak",
    "Asia/Makassar",
    "Asia/Jayapura"
  ],
  "tld": ".id"
},
`;

const matches = [...raw.matchAll(regex)];
const total = matches.length;

(async () => {
  const results = {};
  let current = 0;
  let match;

  regex.lastIndex = 0;

  while ((match = regex.exec(raw)) !== null) {
    current++;
    const code = match[1];
    const block = match[2];

    console.log(`Processing: ${code} (${current}/${total})`);

    const cleanedBlock = `{${block}}`;

    try {
      const res = await geminiCreateContent({
        contents: [{text: cleanedBlock}],
        config: generationConfig,
        systemInstruction: systemInstruction,
        withGrounding: true,
      });

      const text = res.response.text();
      console.log(`Raw output for ${code}:\n${text}\n`);

      let parsed;
      try {
        parsed = JSON.parse(text);
      } catch {
        console.warn(`⚠️ Failed parsing JSON for ${code}. Keeping raw text.`);
        parsed = text;
      }

      results[code] = parsed;
    } catch (err) {
      console.error(`Error processing ${code}`, err);
      results[code] = {error: String(err)};
    }
  }
  const outDir = path.resolve(process.cwd(), "../helpers");
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, {recursive: true});
  }

  const outPath = path.join(outDir, "countries.json");
  fs.writeFileSync(outPath, JSON.stringify(results, null, 2));

  console.log(`✅ DONE. Output saved to ${outPath}`);
})();
