// ⚠️ Auto-generated file. Do not edit manually.

export { default as PersonWithPhone } from './assets/images/illustrations/person_with_phone.svg';
export { default as LogoMerahHitam } from './assets/images/logo/logo_merah_hitam.svg';
export { default as Add } from './assets/images/misc/add.svg';
export { default as ArrowRight } from './assets/images/misc/arrow_right.svg';
export { default as AttachFileAdd } from './assets/images/misc/attach_file_add.svg';
export { default as CalendarMonth } from './assets/images/misc/calendar_month.svg';
export { default as Accessible } from './assets/images/preferences/accessible.svg';
export { default as Budaya } from './assets/images/preferences/budaya.svg';
export { default as BusPublicTransportation } from './assets/images/preferences/bus_public_transportation.svg';
export { default as CityTour } from './assets/images/preferences/city_tour.svg';
export { default as CommuteMixedTransportation } from './assets/images/preferences/commute_mixed_transportation.svg';
export { default as Couple } from './assets/images/preferences/couple.svg';
export { default as Culinary } from './assets/images/preferences/culinary.svg';
export { default as ElderlyWoman } from './assets/images/preferences/elderly_woman.svg';
export { default as GroupFamily } from './assets/images/preferences/group_family.svg';
export { default as GroupFriend } from './assets/images/preferences/group_friend.svg';
export { default as Halal } from './assets/images/preferences/halal.svg';
export { default as History } from './assets/images/preferences/history.svg';
export { default as KidIcon } from './assets/images/preferences/kid_icon.svg';
export { default as Mountain } from './assets/images/preferences/mountain.svg';
export { default as Photography } from './assets/images/preferences/photography.svg';
export { default as PrivateTransport } from './assets/images/preferences/private_transport.svg';
export { default as Shopping } from './assets/images/preferences/shopping.svg';
export { default as SoloTraveler } from './assets/images/preferences/solo_traveler.svg';
